name: Check workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check all scripts for the EXE bit
        run: |
          while IFS= read -r line;
          do
              if [ ! -x $line ];
              then
                  echo "File $line does not have EXE (+x) bit set."
                  exit 1
              fi
          done <<< `find . -type f | grep -E "\.sh$"`
